### ISSUE TITLE
strip_tags instead of esc_html

### ISSUE THREAD

**Issue by newlocalmedia** [chorton2227/WP-Glossary-Hover#1]
`get_tooltip_html` should end with return `sprintf($this->tooltip_html, strip_tags($definition), $term);` instead of `return sprintf($this->tooltip_html, esc_html($definition), $term);` since there is no value in displaying unrendered HTML tags in a tooltip.

**Comment by chorton2227** [comment]
I have updated `get_tooltip_html` to use `strip_tags` 9cd30be98c6ce8042a8cdf3d175051f1abcb417d

**Comment by newlocalmedia** [comment]
Great!
