### ISSUE TITLE
Not Working on PHP earlier than 5.4

### ISSUE THREAD

**Issue by naofireblade** [chorton2227/WP-Glossary-Hover#11]
On PHP 5.3 the plugin gives the following error:
Notice: Use of undefined constant ENT_HTML401
This is caused by the clean_definition method in public/includes/class-tooltip-parser.php . The constant was defined first in PHP 5.4. Replacing the linen
$definition = html_entity_decode($definition, $decoding_flags, $this->encoding);
by
$definition = html_entity_decode($definition); solves the error but than some glossary entries are not rendered on the page.

**Comment by chorton2227** [comment]
Fixed in [version 1.2.3](https://github.com/chorton2227/WP-Glossary-Hover/releases/tag/1.2.3)
