### ISSUE TITLE
Limit length of tooltip

### ISSUE THREAD

**Issue by newlocalmedia** [chorton2227/WP-Glossary-Hover#2]
Since the highlighted term can also be a link to the definition page, and definitions may be quite long, it would make sense to truncate $definition before returning it to the tooltip HTML. 

For example, just the first sentence (text before period+space plus period+space):

		$definition = substr($definition, 0, strrpos($definition,". ")).". "

Or just the first 100 characters:

		return sprintf($this->tooltip_html, strip_tags(substr($definition,0,100)), $term);

etc.

**Comment by chorton2227** [comment]
I have added a setting to limit the number of characters in the tooltip. 148dcf34490a5b356126928a23045e716afb4256

I have also added a setting to link to the glossary term page to see the full definition. d902331d5cb647d0244fa1a5b2d86920f576b8d0

**Comment by naofireblade** [comment]
the ... is also added when limit number of characters is disabled or higher then glossary text.
