### ISSUE TITLE
Tooltip does not function

### ISSUE THREAD

**Issue by chorton2227** [chorton2227/WP-Glossary-Hover#9]
Moved comment from @dockru to new issue.

Tooltip does not function
1) If set limit number to zero, it does not show the text at all,
2) limit only allows 15 characters
3) WP 4.2.2 does not work

**Comment by chorton2227** [comment]
@dockru It works for me with a fresh install of WP. What version of the plugin are you running? Did it work in a previous version?

**Comment by dockru** [comment]
it worked until the plugin was updated to the last version last days

I have WP 4.2.2


Am 19.05.2015 um 18:33 schrieb chorton2227 <notifications@github.com>:

@dockru <https://github.com/dockru> It works for me with a fresh install of WP. What version of the plugin are you running? Did it work in a previous version?

**Comment by chorton2227** [comment]
Does the problem persist when all other plugins are disabled? If so, the plugin may be having trouble with the contents of the definition. Do you mind sharing the definition(s) that are not working correctly? You can email me at chorton2227@gmail.com, if you don't want to post it here.

**Comment by dockru** [comment]
no, there are too many plugins and it works in the Version 1.2.0 on another site.
It’s a problem of updating to Version 1.2.1 for sure




Am 19.05.2015 um 22:41 schrieb chorton2227 <notifications@github.com>:

Does the problem persist when all other plugins are disabled? If so, the plugin may be having trouble with the contents of the definition. Do you mind sharing the definition(s) that are not working correctly? You can email me at chorton2227@gmail.com <mailto:chorton2227@gmail.com>, if you don't want to post it here.

**Comment by dockru** [comment]
no, there are too many plugins and it works in the Version 1.2.0 on another site.
It’s a problem of updating to Version 1.2.1 for sure


Am 19.05.2015 um 22:41 schrieb chorton2227 <notifications@github.com>:

Does the problem persist when all other plugins are disabled? If so, the plugin may be having trouble with the contents of the definition. Do you mind sharing the definition(s) that are not working correctly? You can email me at chorton2227@gmail.com <mailto:chorton2227@gmail.com>, if you don't want to post it here.

**Comment by chorton2227** [comment]
I have fixed an issue with encoding. Let me know if version 1.2.2 fixes your problem.

**Comment by dockru** [comment]
yes, it’s fixed


Am 20.05.2015 um 01:33 schrieb chorton2227 <notifications@github.com>:

I have fixed an issue with encoding. Let me know if version 1.2.2 fixes your problem.

**Comment by chorton2227** [comment]
Thanks for reporting the issue.
